# https://taskfile.dev

version: '3'

tasks:

    git:tag:patch:
      desc: Add git tag, but upgrade latest patch version
      cmds:
        - cmd: git tag \
            -a "v$(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 || echo 0).$(git tag | sort -V | tail -1 | cut -d'.' -f2 || echo 0).$(($(git tag | sort -V | tail -1 | cut -d'.' -f3 || echo 0)+1))" \
            -m "v$(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 || echo 0).$(git tag | sort -V | tail -1 | cut -d'.' -f2 || echo 0).$(($(git tag | sort -V | tail -1 | cut -d'.' -f3 || echo 0)+1))"
          silent: true

    git:tag:minor:
      desc: Add git tag, but upgrade latest minor version
      cmds:
        - cmd: git tag \
            -a "v$(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 || echo 0).$(($(git tag | sort -V | tail -1 | cut -d'.' -f2 || echo 0)+1)).$(git tag | sort -V | tail -1 | cut -d'.' -f3 || echo 0)" \
            -m "v$(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 || echo 0).$(($(git tag | sort -V | tail -1 | cut -d'.' -f2 || echo 0)+1)).$(git tag | sort -V | tail -1 | cut -d'.' -f3 || echo 0)"
          silent: true

    git:tag:major:
      desc: Add git tag, upgrade latest major version
      cmds:
        - cmd: git tag \
            -a "v$(($(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 || echo 0)+1)).$(git tag | sort -V | tail -1 | cut -d'.' -f2 || echo 0).$(git tag | sort -V | tail -1 | cut -d'.' -f3 || echo 0)" \
            -m "v$(($(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 || echo 0)+1)).$(git tag | sort -V | tail -1 | cut -d'.' -f2 || echo 0).$(git tag | sort -V | tail -1 | cut -d'.' -f3 || echo 0)"
          silent: true
    
    git:tag:deletelatest:
      desc: Delete latest (local) tag
      cmds:
        - cmd: git tag -d $(git tag | sort -V | tail -1)
          silent: true

    release:patch:
      desc: Create new patch version tag and push
      cmds:
        - task: git:tag:patch
        - cmd: git push --follow-tags
          silent: true
    release:minor:
      desc: Create new minor version tag and push
      cmds:
        - task: git:tag:minor
        - cmd: git push --follow-tags
          silent: true

    release:major:
      desc: Create new major version tag and push
      cmds:
        - task: git:tag:major
        - cmd: git push --follow-tags
          silent: true
