# https://taskfile.dev

version: '3'

tasks:

    git:tag:patch:
      desc: Add git tag, but upgrade latest patch version
      cmds:
        - cmd: git tag -a "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}" -m "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}"
          silent: true
      vars:
        MAJOR:
          sh: git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1
        MINOR:
          sh: git tag | sort -V | tail -1 | cut -d'.' -f2
        PATCH:
          sh: echo "$(($(git tag | sort -V | tail -1 | cut -d'.' -f3 )+1))"
    git:tag:minor:
      desc: Add git tag, but upgrade latest minor version
      cmds:
        - cmd: git tag -a "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}" -m "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}"
          silent: true
      vars:
        MAJOR:
          sh: git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1
        MINOR:
          sh: echo "$(($(git tag | sort -V | tail -1 | cut -d'.' -f2 )+1))"
        PATCH: "0"
    git:tag:major:
      desc: Add git tag, upgrade latest major version
      cmds:
        - cmd: git tag -a "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}" -m "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}"
          silent: true
      vars:
        MAJOR:
          sh: echo "$(($(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 )+1))"
        MINOR: "0"
        PATCH: "0"
    git:tag:deletelatest:
      desc: Delete latest (local) tag
      cmds:
        - cmd: git tag -d $(git tag | sort -V | tail -1)
          silent: true

    release:patch:
      desc: Create new patch version tag and push
      cmds:
        - task: git:tag:patch
        - cmd: printf "# Changelog\n\n- \n" > CHANGELOG.md
          silent: true
        - cmd: (git add CHANGELOG.md 2>/dev/null && git commit -m "Resetted changelog" >/dev/null) || (echo "Please edit the changelog first" && task global:git:tag:deletelatest && exit 1)
          silent: true
        - cmd: git push --follow-tags
          silent: true
    release:minor:
      desc: Create new minor version tag and push
      cmds:
        - task: git:tag:minor
        - cmd: printf "# Changelog\n\n- \n" > CHANGELOG.md
          silent: true
        - cmd: (git add CHANGELOG.md 2>/dev/null && git commit -m "Resetted changelog" >/dev/null) || (echo "Please edit the changelog first" && task global:git:tag:deletelatest && exit 1)
          silent: true
        - cmd: git push --follow-tags
          silent: true
    release:major:
      desc: Create new major version tag and push
      cmds:
        - task: git:tag:major
        - cmd: printf "# Changelog\n\n- \n" > CHANGELOG.md
          silent: true
        - cmd: (git add CHANGELOG.md 2>/dev/null && git commit -m "Resetted changelog" >/dev/null) || (echo "Please edit the changelog first" && task global:git:tag:deletelatest && exit 1)
          silent: true
        - cmd: git push --follow-tags
          silent: true

    git:branch:help:
      desc: Show common commands for git branches
      cmds:
        - cmd: |
            printf "%-40s%s\n" "> git branch -d <name>" "Delete local branch"
            printf "%-40s%s\n" "> git push origin --delete <name>" "Delete remote branch"
            printf "%-40s%s\n" "> git branch <name>" "Create local branch"
            printf "%-40s%s\n" "> git checkout -b <name>" "Create local branch and check it out"
          silent: true
    
    git:deletelatestcommitkeepchanges:
      desc: Delete latest commit (singular!) but keep changes
      cmds:
        - git reset "HEAD^"

    gpg:setup:
      desc: Set your gpg key up and tell git about it
      cmds:
        - cmd: |
            echo "%echo Generating gpg key
            Key-Type: RSA
            Key-Length: 4096
            Subkey-Type: RSA
            Subkey-Length: 4096
            Name-Real: {{ .REALNAME }}
            Name-Email: {{ .EMAIL }}
            Expire-Date: 0
            %no-protection
            # Do a commit here, so that we can later print "done" :-)
            %commit
            %echo done
            " > gpgconfig
          silent: true
        - cmd: gpg --batch --generate-key gpgconfig
          silent: true
        - cmd: rm gpgconfig
          silent: true
        - cmd: git config --global user.signingkey $(gpg --list-secret-keys --keyid-format LONG | grep "sec" | cut -d' ' -f4 | cut -d'/' -f2)
          silent: true
        - cmd: git config --global commit.gpgsign true
          silent: true
        - cmd: gpg --armor --export $(gpg --list-secret-keys --keyid-format LONG | grep "sec" | cut -d' ' -f4 | cut -d'/' -f2)
          silent: true
        - cmd: echo "Now you only need to tell github (https://github.com/settings/keys) and vscode (setting git.enableCommitSigning) about it :)"
          silent: true
      vars:
        REALNAME: "Till Hoffmann"
        EMAIL: "till.hoffmann@enforge.de"
