# https://taskfile.dev

version: '3'

output: prefixed

tasks:

    git:tag:patch:
      desc: Add git tag, but upgrade latest patch version
      cmds:
        - cmd: git tag -a "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}" -m "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}"
          silent: true
      vars:
        MAJOR:
          sh: git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1
        MINOR:
          sh: git tag | sort -V | tail -1 | cut -d'.' -f2
        PATCH:
          sh: echo "$(($(git tag | sort -V | tail -1 | cut -d'.' -f3 )+1))"
    git:tag:minor:
      desc: Add git tag, but upgrade latest minor version
      cmds:
        - cmd: git tag -a "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}" -m "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}"
          silent: true
      vars:
        MAJOR:
          sh: git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1
        MINOR:
          sh: echo "$(($(git tag | sort -V | tail -1 | cut -d'.' -f2 )+1))"
        PATCH:
          sh: git tag | sort -V | tail -1 | cut -d'.' -f3
    git:tag:major:
      desc: Add git tag, upgrade latest major version
      cmds:
        - cmd: git tag -a "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}" -m "v{{ default "0" .MAJOR }}.{{ default "0" .MINOR }}.{{ default "0" .PATCH }}"
          silent: true
      vars:
        MAJOR:
          sh: echo "$(($(git tag | sort -V | tail -1 | cut -d'v' -f2 | cut -d'.' -f1 )+1))"
        MINOR:
          sh: git tag | sort -V | tail -1 | cut -d'.' -f2
        PATCH:
          sh: git tag | sort -V | tail -1 | cut -d'.' -f3
    git:tag:deletelatest:
      desc: Delete latest (local) tag
      cmds:
        - cmd: git tag -d $(git tag | sort -V | tail -1)
          silent: true

    release:patch:
      desc: Create new patch version tag and push
      cmds:
        - task: git:tag:patch
        - cmd: git push --follow-tags
          silent: true
    release:minor:
      desc: Create new minor version tag and push
      cmds:
        - task: git:tag:minor
        - cmd: git push --follow-tags
          silent: true
    release:major:
      desc: Create new major version tag and push
      cmds:
        - task: git:tag:major
        - cmd: git push --follow-tags
          silent: true

    git:branch:help:
      desc: Show common commands for git branches
      cmds:
        - cmd: |
            printf "%-40s%s\n" "> git branch -d <name>" "Delete local branch"
            printf "%-40s%s\n" "> git push origin --delete <name>" "Delete remote branch"
            printf "%-40s%s\n" "> git branch <name>" "Create local branch"
            printf "%-40s%s\n" "> git checkout -b <name>" "Create local branch and check it out"
          silent: true
